services:
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    container_name: qube-api
    ports:
      - '8080:8080'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    #      - "PATH_TO_SERVERFILES:/app/server"
    environment:
      - TRAEFIK_ENABLED=true
      - TRAEFIK_ENTRYPOINT=web
      - DOMAIN=qube.letsdrinksometea.de
      - NODE_ENV=production
      - CF_API_KEY
    restart: always
    develop:
      watch:
        - action: sync
          path: ./apps/api
          target: /app/apps/api
          ignore:
            - node_modules
        - action: rebuild
          path: ./apps/api/package.json

  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile.dev
    container_name: qube-web
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_API_URL=http://api:8080
      - CF_API_KEY
    depends_on:
      - api
    restart: always
    develop:
      watch:
        - action: sync
          path: ./apps/web
          target: /app/apps/web
          ignore:
            - node_modules
            - .next
            - dist
            - .git
        - action: rebuild
          path: ./apps/app/web/package.json

  traefik:
    image: traefik:v3.6
    command:
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--entrypoints.web.address=:80'
      - '--providers.docker.exposedbydefault=false'
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - 'traefik.enable=true'
      ## HTTP Routers
      - 'traefik.http.routers.traefik-rtr.rule=Host(`traefik.qube.letsdrinksometea.de`)'
      - 'traefik.http.routers.traefik-rtr.entrypoints=web' # Defined in traefik.yaml
      - 'traefik.http.routers.traefik-rtr.service=api@internal'
    networks:
      - qube-server-network

networks:
  qube-server-network:
    external: true
